BROWSER = "firefox"
TERM_EMULATOR = "kitty"
TERM_EMULATOR_TWO = "sakura"
TERM_EMULATOR_THREE = "alacritty"
EDITOR = "code"
PASSWORDMANAGER="bitwarden-desktop"
GITMANAGER="gitkraken"
MAIL = "thunderbird-beta"
FILEMANAGER = "thunar"
MUSIC_PLAYER = "spotify"
WALLPAPER = "sh -c ~/Scripts/wallpaper.sh"
CLIPBOARD = "roficlip"
SCREENSHOT = "flameshot full -p /home/mhiri/Pictures/Screenshots"
COLORPICKER = "sh -c ~/Scripts/colorpicker.sh"
ROFI = "rofi -show drun"
ROFIPOWER = "sh -c ~/.config/rofi/scripts/power"
DMENU = "dmenu_run -i -nb '#1e1e2e' -nf '#74c7ec' -sb '#cba6f7' -sf '#1e1e2e' -fn 'NotoMonoRegular:bold:pixelsize=24'"
HOTEL = "trivago"