BROWSER = "firefox"
TERM_EMULATOR = "kitty"
EDITOR = "code"
PASSWORDMANAGER="bitwarden-desktop"
GITMANAGER="gitkraken"
MAIL = "thunderbird-beta"
FILEMANAGER = "thunar"
MUSIC_PLAYER = "spotify"
WALLPAPER = "sh -c ~/Scripts/wallpaper.sh"
CLIPBOARD = "roficlip"
SCREENSHOT = "flameshot full -p /home/mhiri/Pictures/Screenshots"
COLORPICKER = "sh -c ~/Scripts/colorpicker.sh"
ROFI = "rofi -show drun"
ROFIPOWER = "sh -c ~/.config/rofi/scripts/power"
DMENU = "dmenu_run -i -nb '#2A2F3A' -nf '#88c0d0' -sb '#88c0d0' -sf '#2A2F3A' -fn 'NotoMonoRegular:bold:pixelsize=20'"
HOTEL = "trivago"
